FROM golang:1.16
WORKDIR /app
COPY . .
WORKDIR /app/cmd/devices
RUN go mod download
WORKDIR /app
RUN CGO_ENABLED=0 go build -o devices ./cmd/devices/main.go

FROM scratch
COPY --from=0 /app/devices /
CMD ["/devices"]
