name: Main Workflow

on:
  push:
    branches:
      - develop
      - master

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run Test
        run:
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

      - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@v1.1
        with:
          filename: coverage.out

      - name: Automatic Tag (Bump version and push tag)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches : "master,main,develop"
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lamassuiot/lamassu-dms-enroller:${{ steps.tag_version.outputs.new_tag }}

        
      - name: Tag Docker image as latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lamassuiot/lamassu-dms-enroller:latest